title: Kari's Portfolio

show_downloads: true
google_analytics:
theme: jekyll-theme-architect
collections:
  recipes:
    output: true

defaults:
  - scope:
      path: ""
      type: "recipes"
    values:
      layout: "recipe"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"