title: Kari's Portfolio
description: This is my portfolio of things I like and things I have done.
show_downloads: true
google_analytics:
theme: jekyll-theme-architect
collections:
  recipes:
    output: true

defaults:
  - scope:
      path: ""
      type: "recipes"
    values:
      layout: "recipe"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"